### ISSUE TITLE
Unable to run many fastlane commands

### ISSUE THREAD

**Issue by davidrothera** [KrauseFx/fastlane#241]
Hey, fresh OSX install and so reinstalling everything and running into this issue:

```
drothera-mbp:Project drothera$ sigh --help
(erb):2:in `get_binding': undefined method `size' for nil:NilClass (NoMethodError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/help_formatters/terminal.rb:7:in `render'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:302:in `block (2 levels) in create_default_co
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:57:in `block in run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:382:in `block in global_option_proc'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `call'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `block in parse_in_or
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:363:in `parse_global_options'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:65:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-0.4.10/bin/sigh:52:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-0.4.10/bin/sigh:59:in `<top (required)>'
        from /usr/bin/sigh:23:in `load'
        from /usr/bin/sigh:23:in `<main>'
```

fastlane version is 0.12.5

**Comment by KrauseFx** [comment]
Sorry, with the latest version of `commander` the `--help` command of all tools broke, I'm working on a fix :+1:

**Comment by davidrothera** [comment]
Awesome, thought it was something to do with my fresh Ruby env :+1:

**Comment by KrauseFx** [comment]
Fixed with https://github.com/KrauseFx/fastlane/commit/63757c6dcccaec1f4e23305a1cb5adb959ec8fb9, thanks again for reporting :+1:

**Comment by davidrothera** [comment]
Im still seeing the same error, what version will this fix be rolled in?

**Comment by KrauseFx** [comment]
With the latest version of `fastlane`. Did you update? What happens when you run `sigh --help`?

**Comment by KrauseFx** [comment]
Also, you can run `sigh -v` to make sure you're on `0.5.0`

**Comment by davidrothera** [comment]
Ok, looks like I was just being a bit quick off the bat with the gem update, the specs repo just hadn't caught up.

Re-updated and now all looking good :) :+1:

**Comment by KrauseFx** [comment]
Great to hear :+1:

**Comment by davidrothera** [comment]
Hey, just checking in to say that in cert v0.1.9 I am still seeing the same issues as before :-1: 

```
drothera-mbp:SugarFix drothera$ cert --help
(erb):2:in `get_binding': undefined method `size' for nil:NilClass (NoMethodError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/help_formatters/terminal.rb:7:in `render'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:302:in `block (2 levels) in create_default_commands'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:57:in `block in run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:382:in `block in global_option_proc'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `call'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `block in parse_in_order'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:363:in `parse_global_options'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/runner.rb:65:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/cert-0.1.9/bin/cert:40:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/cert-0.1.9/bin/cert:46:in `<top (required)>'
        from /usr/bin/cert:23:in `load'
        from /usr/bin/cert:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Please update using `sudo gem update fastlane_core` and let me know if that works! :+1:

**Comment by KrauseFx** [comment]
Oh, I didn't update `cert` yet as it seems: https://github.com/KrauseFx/cert/releases
