### ISSUE TITLE
sigh can't find app_identifier after hiding fastlane folder

### ISSUE THREAD

**Issue by armadsen** [KrauseFx/fastlane#701]
I'd like to hide my fastlane folder, as documented [here](https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md). However, after renaming it to '.fastlane', the next time I run fastlane, the sigh step complains that the app_identifier isn't set. This is despite that fact that it is set in the Appfile.

Without having dug into this at all, it seems like perhaps fastlane and/or sigh doesn't find the Appfile if it's inside a hidden .fastlane folder.

**Comment by KrauseFx** [comment]
Nice catch, I'll look into it

**Comment by KrauseFx** [comment]
I pushed a fix, please update using `sudo gem update credentials_manager`

**Comment by KrauseFx** [comment]
Let me know if that works for you :+1:

**Comment by armadsen** [comment]
Thanks Felix! I'll check it out just as soon as I can and comment again if I'm still seeing the problem.
